changes made in the run script

diff --git a/models/E3SM-FV/shell_scripts/e3sm_cam5/assimilate.csh.template b/models/E3SM-FV/shell_scripts/e3sm_cam5/assimilate.csh.template
--- a/models/E3SM-FV/shell_scripts/e3sm_cam5/assimilate.csh.template
+++ b/models/E3SM-FV/shell_scripts/e3sm_cam5/assimilate.csh.template
@@ -9,18 +9,18 @@
 # ------------------------------------------------------------------------------
 # Purpose: assimilate with a CAM ensemble and perform advanced archiving
 #          and compression in support of multiple assimilation cycles in a
-#          single E3SM job.
+#          single E3SM-FV job.
 #
-# The (resulting) assimilate.csh script is called by E3SM with two arguments:
+# The (resulting) assimilate.csh script is called by E3SM-FV with two arguments:
 # 1) the CASEROOT, and
-# 2) the assimilation cycle number in this E3SM job
+# 2) the assimilation cycle number in this E3SM-FV job
 # ------------------------------------------------------------------------------
 # This template is lightly modified by the setup scripts to be appropriate
 # for specific hardware and other configurations. The modified result is
 # then given execute permission and is appropriate to use for an assimilation.
 # All of this is automatically performed by the DART-supplied setup scripts.
 #
-# Tag DART's state output with names using E3SM's convention:
+# Tag DART's state output with names using E3SM-FV's convention:
 #    ${case}.${scomp}[_$inst].${filetype}[.$dart_file].${date}.nc
 #    These should all be named with $scomp = "cam" to distinguish
 #    them from the same output from other components in multi-component assims.
@@ -39,65 +39,42 @@
 # and the 18Z gets restaged
 
 # machine-specific dereferencing
+# suppress "rm" warnings if wildcard does not match anything
+set nonomatch
 
-if ($?SLURM_JOB_ID) then
+switch ("`hostname`")
+   case cori*:
+      # NERSC "cori"
+      set   MOVE = '/usr/bin/mv -fv'
+      set   COPY = '/usr/bin/cp -fv --preserve=timestamps'
+      set   LINK = '/usr/bin/ln -fvs'
+      set   LIST = '/usr/bin/ls '
+      set REMOVE = '/usr/bin/rm -fr'
+      set  LAUNCHCMD = mpirun.lsf
+   breaksw
 
-   # SLURM environment variables:
-   # env | grep SLURM | sort
+   case compy*:
+      # PNNL "compy"
+      set   MOVE = '/usr/bin/mv -fv'
+      set   COPY = '/usr/bin/cp -fv --preserve=timestamps'
+      set   LINK = '/usr/bin/ln -fvs'
+      set   LIST = '/usr/bin/ls '
+      set REMOVE = '/usr/bin/rm -fr'
 
-   setenv ORIGINALDIR $SLURM_SUBMIT_DIR
-   setenv     JOBNAME $SLURM_JOB_NAME
-   setenv       JOBID $SLURM_JOBID
-   setenv     MYQUEUE $SLURM_JOB_PARTITION
-   setenv   NODENAMES $SLURM_NODELIST
-   setenv LAUNCHCMD "srun --mpi=pmi2 --ntasks=24 --kill-on-bad-exit -l --cpu_bind=cores"
-#"srun -np $SLURM_NTASKS -bind-to core"
-#  untested method for determining NUMTASKS_PERNODE with SLURM
-#  set ANY_OLD_NODE = `head -n 1 $SLURM_NODELIST`
-#  setenv NUMTASKS_PERNODE `grep $ANY_OLD_NODE $SLURM_NODELIST | wc -l`
+      #This next line ultimately specifies the location of the observation files.
+      set  LAUNCHCMD = "srun --mpi=pmi2 --ntasks=BOGUSNTASKS --kill-on-bad-exit -l --cpu_bind=cores -c 4 -m plane=40"
+   breaksw
 
-else if ($?PBS_NODEFILE) then
-
-   # PBS environment variables:
-   # env | grep PBS | sort
-
-   setenv ORIGINALDIR $PBS_O_WORKDIR
-   setenv     JOBNAME $PBS_JOBNAME
-   setenv       JOBID $PBS_JOBID
-   setenv     MYQUEUE $PBS_O_QUEUE
-   setenv     NUMCPUS $NCPUS
-   setenv    NUMTASKS `cat  $PBS_NODEFILE | wc -l`
-   setenv    NUMNODES `uniq $PBS_NODEFILE | wc -l`
-   set ANY_OLD_NODE = `head -n 1 $PBS_NODEFILE`
-   setenv    NUMTASKS_PERNODE `grep $ANY_OLD_NODE $PBS_NODEFILE | wc -l`
-   setenv  MPIEXEC_MPT_DEBUG 0
-   setenv MP_DEBUG_NOTIMEOUT yes
-   setenv          LAUNCHCMD mpiexec_mpt
-
-   echo "jobname        : $JOBNAME"
-   echo "numcpus        : $NUMCPUS"
-   echo "numtasks       : $NUMTASKS"
-   echo "numnodes       : $NUMNODES"
-   echo "tasks_per_node : $NUMTASKS_PERNODE"
-   echo " "
-
-else if ($?LSB_HOSTS) then
-
-   # LSF environment variables:
-   # env | grep LS | grep -v LS_COLORS | sort
-
-   setenv ORIGINALDIR $LS_SUBCWD
-   setenv     JOBNAME $LSB_OUTPUTFILE:ar
-   setenv       JOBID $LSB_JOBID
-   setenv     MYQUEUE $LSB_QUEUE
-   setenv   NODENAMES ${LSB_HOSTS}
-   setenv MP_DEBUG_NOTIMEOUT yes
-   setenv LAUNCHCMD mpirun.lsf
-#  untested method for determining NUMTASKS_PERNODE with LSF
-#  setenv NUMTASKS_PERNODE \
-#     `echo $LSB_SUB_RES_REQ | sed -ne '/ptile/s#.*\[ptile=\([0-9][0-9]*\)]#\1#p'`
-
-endif
+   default:
+      set   MOVE = 'mv -fv'
+      set   COPY = 'cp -fv --preserve=timestamps'
+      set   LINK = 'ln -fvs'
+      set   LIST = '/usr/bin/ls '
+      set REMOVE = 'rm -fr'
+      #This next line ultimately specifies the location of the observation files.
+      set  LAUNCHCMD = "srun --mpi=pmi2 --ntasks=BOGUSNTASKS --kill-on-bad-exit -l --cpu_bind=cores -c 1 -m plane=40 "
+   breaksw
+endsw
 
 # ==============================================================================
 # Block 0: Set command environment
@@ -108,11 +85,9 @@ endif
 
 echo "`date` -- BEGIN CAM_ASSIMILATE"
 
-set nonomatch      # suppress "rm" warnings if wildcard does not match anything
-
 setenv CASEROOT $1
 
-# E3SM uses C indexing on loops; cycle = [0,....,$DATA_ASSIMILATION_CYCLES - 1]
+# E3SM-FV uses C indexing on loops; cycle = [0,....,$DATA_ASSIMILATION_CYCLES - 1]
 # "Fix" that here, so the rest of the script isn't confusing.
 
 @ cycle = $2 + 1
@@ -131,11 +106,42 @@ setenv CONT_RUN                  `./xmlquery CONTINUE_RUN  --value`
 setenv CHECK_TIMING              `./xmlquery CHECK_TIMING  --value`
 setenv DATA_ASSIMILATION_CYCLES  `./xmlquery DATA_ASSIMILATION_CYCLES --value`
 
-# Switch E3SM's timer script off for the rest of the forecasts of this job.
+# Switch E3SM-FV's timer script off for the rest of the forecasts of this job.
 # The timer takes a significant amount of time, which grows by ~15 s
 # for each cycle.  This can double the cycle time in a 2 week job.
 
 ./xmlchange CHECK_TIMING=FALSE
+
+###setup the namelist for E3SM continuous run#####
+set FILE = `head -n 1 ${RUNDIR}/rpointer.atm_0001`
+set FILE = $FILE:r
+set ATM_DATE_EXT = $FILE:e
+set ATM_DATE     = `echo $FILE:e | sed -e "s#-# #g"`
+set reftimestamp = $ATM_DATE[1]-$ATM_DATE[2]-$ATM_DATE[3]-$ATM_DATE[4]
+echo $reftimestamp
+
+set inst = 1
+while ($inst <= $ensemble_size)
+   # following the E3SM strategy for 'inst_string'
+   set inst_string = `printf _%04d $inst`
+   set fname = "user_nl_cam${inst_string}"
+   sed -i '/ncdata/d' $fname
+   echo " ncdata        = 'cam_initial${inst_string}.nc'" >> ${fname}
+   set fname = "user_nl_clm${inst_string}"
+   sed -i '/finidat/d' $fname
+   echo "finidat = '${CASE}.clm2${inst_string}.r.${reftimestamp}.nc'" >> ${fname}
+   set fname = "user_nl_cice${inst_string}"
+   sed -i '/ice_ic/d' $fname
+   echo "ice_ic = '${CASE}.cice${inst_string}.r.${reftimestamp}.nc'" >> ${fname}
+   @ inst ++
+end
+./preview_namelists || exit 75
+
+#change the RUN_REFDATE RUN_REFTOD RUN_STARTDATE START_TOD
+./xmlchange RUN_REFDATE=$ATM_DATE[1]-$ATM_DATE[2]-$ATM_DATE[3]
+./xmlchange RUN_REFTOD=$ATM_DATE[4]
+./xmlchange RUN_STARTDATE=$ATM_DATE[1]-$ATM_DATE[2]-$ATM_DATE[3]
+./xmlchange START_TOD=$ATM_DATE[4]
 
 cd ${RUNDIR}
 
@@ -152,22 +158,6 @@ setenv save_stages_freq RESTART_TIMES
 
 # This next line ultimately specifies the location of the observation files.
 set BASEOBSDIR = BOGUSBASEOBSDIR
-
-# suppress "rm" warnings if wildcard does not match anything
-set nonomatch
-
-# Make sure that this script is using standard system commands
-# instead of aliases defined by the user.
-# If the standard commands are not in the location listed below,
-# change the 'set' commands to use them.
-# The VERBOSE options are useful for debugging, but are optional because
-# some systems don't like the -v option to any of the following.
-
-set   MOVE = '/usr/bin/mv -v'
-set   COPY = '/usr/bin/cp --preserve=timestamps'
-set   LINK = '/usr/bin/ln -s'
-set   LIST = '/usr/bin/ls '
-set REMOVE = '/usr/bin/rm -r'
 
 # ==============================================================================
 # Block 1: Determine time of current model state from file name of member 1
@@ -199,7 +189,7 @@ if ($status == 0) then
 endif
 
 # We need to know the names of the current e3sm.log files - one log file is created
-# by each E3SM model advance.
+# by each E3SM-FV model advance.
 
 set log_list = `${LIST} -t e3sm.log.*`
 
@@ -312,7 +302,7 @@ endif
 # ==============================================================================
 # Block 4: Preliminary clean up, which can run in the background.
 # ==============================================================================
-# E3SM2_0's new archiver has a mechanism for removing restart file sets,
+# E3SM-FV2_0's new archiver has a mechanism for removing restart file sets,
 # which we don't need, but it runs only after the (multicycle) job finishes.
 # We'd like to remove unneeded restarts as the job progresses, allowing more
 # cycles to run before needing to stop to archive data.  So clean them out of
@@ -378,8 +368,8 @@ if ($#log_list >= 3) then
       # Note that *cpl.h[ar]* are retained, and any h#, #>0.
 
       echo "Removing unneeded restart file set (DD_SSSSS ${day_time}) from RUNDIR: "
-      echo "     ${CASE}"'*.{r,rs,rs1,rh0,h0,h1}.*'"${day_time}"
-      ${REMOVE}  ${CASE}*.{r,rs,rs1,rh0,h0,h1}.*${day_time}* &
+      echo "     ${CASE}"'*.{r,rs,rs1,rh0,h1}.*'"${day_time}"
+      ${REMOVE}  ${CASE}*.{r,rs,rs1,rh0,h1}.*${day_time}* &
 
       # Handle .i. separately to avoid sweeping up .i.${scomp}_{in,out}put_{mean,sd,...} files.
       echo "     ${CASE}"'*.i.[0-9]*'"${day_time}"
@@ -426,7 +416,7 @@ if ($#log_list >= 3) then
       set save_root = ${archive}/rest/${rm_date}
       if (! -d $save_root) then
          mkdir -p $save_root
-         (${MOVE} ${CASE}*.{r,rs,rs1,rh0,h0,h1}.*${day_time}*  $save_root || exit 60) &
+         (${MOVE} ${CASE}*.{r,rs,rs1,rh0,h1}.*${day_time}*  $save_root || exit 60) &
          (${MOVE} ${CASE}*.i.[0-9]*${day_time}*             $save_root || exit 61) &
          (${COPY} *.output*inf*${day_time}*                 $save_root || exit 62) &
          (${MOVE} *0001*${rm_log[$rm_slot]}*                $save_root || exit 63) &
@@ -441,7 +431,7 @@ if ($#log_list >= 3) then
    ${REMOVE}  [^d]*${rm_log[$rm_slot]}*  &
 
    # I'd like to remove the CAM .r. files, since we always use the .i. files to do a hybrid start,
-   # but apparently E3SM needs them to be there, even though it doesn't read fields from them.
+   # but apparently E3SM-FV needs them to be there, even though it doesn't read fields from them.
    # ${REMOVE}  ${CASE}.cam*.r.*${day_time}.nc &
 
 endif
@@ -456,16 +446,16 @@ endif
 
 set YYYYMM = `printf %04d%02d ${ATM_YEAR} ${ATM_MONTH}`
 
-if (! -d ${BASEOBSDIR}/${YYYYMM}_6H_E3SM) then
-   echo "E3SM+DART requires 6 hourly obs_seq files in directories of the form YYYYMM_6H_E3SM"
-   echo "The directory ${BASEOBSDIR}/${YYYYMM}_6H_E3SM is not found.  Exiting"
+if (! -d ${BASEOBSDIR}/${YYYYMM}_6H_E3SM-FV) then
+   echo "E3SM-FV+DART requires 6 hourly obs_seq files in directories of the form YYYYMM_6H_E3SM-FV"
+   echo "The directory ${BASEOBSDIR}/${YYYYMM}_6H_E3SM-FV is not found.  Exiting"
    exit 70
 endif
 
 #set OBSFNAME = `printf obs_seq.%04d-%02d-%02d-%05d ${ATM_YEAR} ${ATM_MONTH} ${ATM_DAY} ${ATM_SECONDS}`
 set OBSFNAME = `printf obs_seq%04d%02d%02d%02d ${ATM_YEAR} ${ATM_MONTH} ${ATM_DAY} ${ATM_HOUR}`
 
-set OBS_FILE = ${BASEOBSDIR}/${YYYYMM}_6H_E3SM/${OBSFNAME}
+set OBS_FILE = ${BASEOBSDIR}/${YYYYMM}_6H_E3SM-FV/${OBSFNAME}
 echo "OBS_FILE = $OBS_FILE"
 
 ${REMOVE} obs_seq.out
@@ -488,7 +478,7 @@ endif
 #
 # This block stages the files that contain the inflation values.
 # The inflation files are essentially duplicates of the DART model state,
-# which have names in the E3SM style, something like
+# which have names in the E3SM-FV style, something like
 #    ${case}.dart.rh.${scomp}_output_priorinf_{mean,sd}.YYYY-MM-DD-SSSSS.nc
 # The strategy is to use the latest such files in ${RUNDIR}.
 # If those don't exist at the start of an assimilation,
@@ -499,7 +489,7 @@ endif
 # with the current forecast time, so check that the inflation mean
 # files are evolving as expected.
 #
-# E3SM's st_archive should archive the inflation restart files
+# E3SM-FV's st_archive should archive the inflation restart files
 # like any other "restart history" (.rh.) files; copying the latest files
 # to the archive directory, and moving all of the older ones.
 # ==============================================================================
@@ -515,12 +505,13 @@ ${LINK} ${CASE}.cam_0001.i.${ATM_DATE_EXT}.nc ${CAMINPUT} || exit 90
 
 # All of the .h1. files contain the same PHIS field, so we can link to any of them.
 
-set hists = `${LIST} ${CASE}.cam_0001.h1.*.nc`
+#set hists = `${LIST} ${CASE}.cam_0001.h1.*.nc`
 set MYSTRING = `grep cam_phis_filename input.nml`
 set MYSTRING = `echo $MYSTRING | sed -e "s#[=,']# #g"`
 set CAM_PHIS = $MYSTRING[2]
 ${REMOVE} ${CAM_PHIS}
-${LINK} $hists[1] ${CAM_PHIS} || exit 100
+${LINK} ${CASE}.cam_0001.h1.${ATM_DATE_EXT}.nc ${CAM_PHIS} || exit 100
+#${LINK} $hists[1] ${CAM_PHIS} || exit 100
 
 # Now, actually check the inflation settings
 
@@ -695,7 +686,7 @@ endif
 #
 # DART namelist settings required:
 # &filter_nml
-#    adv_ens_command         = "no_E3SM_advance_script",
+#    adv_ens_command         = "no_E3SM-FV_advance_script",
 #    obs_sequence_in_name    = 'obs_seq.out'
 #    obs_sequence_out_name   = 'obs_seq.final'
 #    single_file_in          = .false.,
@@ -717,11 +708,11 @@ endif
 # The name of the text file is provided to filter in filter_nml:input_state_file_list.
 
 # NOTE:
-# If the files in input_state_file_list are E3SM initial files (all vars and
+# If the files in input_state_file_list are E3SM-FV initial files (all vars and
 # all meta data), then they will end up with a different structure than
 # the non-'output', stage output written by filter ('preassim', 'postassim', etc.).
 # This can be prevented (at the cost of more disk space) by copying
-# the E3SM format initial files into the names filter will use for preassim, etc.:
+# the E3SM-FV format initial files into the names filter will use for preassim, etc.:
 #    > cp $case.cam_0001.i.$date.nc  preassim_member_0001.nc.
 #    > ... for all members
 # Filter will replace the state variables in preassim_member* with updated versions,
@@ -757,10 +748,10 @@ ${LAUNCHCMD} ${EXEROOT}/filter || exit 140
 echo "`date` -- END FILTER"
 
 # ==============================================================================
-# Block 8: Rename the output using the E3SM file-naming convention.
+# Block 8: Rename the output using the E3SM-FV file-naming convention.
 # ==============================================================================
 
-# If output_state_file_list is filled with custom (E3SM) filenames,
+# If output_state_file_list is filled with custom (E3SM-FV) filenames,
 # then 'output' ensemble members will not appear with filter's default,
 # hard-wired names.  But file types output_{mean,sd} will appear and be
 # renamed here.
@@ -781,7 +772,7 @@ echo "`date` -- END FILTER"
 echo "`date` -- BEGIN FILE RENAMING"
 
 # The short-term archiver archives files depending on pieces of their names.
-# '_####.i.' files are E3SM initial files.
+# '_####.i.' files are E3SM-FV initial files.
 # '.dart.i.' files are ensemble statistics (mean, sd) of just the state variables 
 #            in the initial files.
 # '.e.'      designates a file as something from the 'external system processing ESP', e.g. DART.
@@ -862,7 +853,7 @@ endif
 
 # Then this script will need to feed the files in output_restart_list_file
 # to the next model advance.
-# This gets the .i. or .r. piece from the E3SM format file name.
+# This gets the .i. or .r. piece from the E3SM-FV format file name.
 set line = `grep 0001 $output_file_list_name | sed -e "s#[\.]# #g"`
 set l = 1
 while ($l < $#line)
@@ -929,7 +920,7 @@ if ($cycle == $DATA_ASSIMILATION_CYCLES) then
       endif
 
       # Hide the CAM 'restart' files from the previous cycle (day_time) from the archiver.
-      ${MOVE}           ${CASE}*.{r,rs,rs1,rh0,h0,h1,i}.*${day_time}*    $hidedir
+      ${MOVE}           ${CASE}*.{r,rs,rs1,rh0,h1,i}.*${day_time}*    $hidedir
 
       # Move log files: *YYMMDD-HHMMSS.  [2] means the previous restart set is being moved.
       set rm_log = `echo $log_list[2] | sed -e "s/\./ /g;"`
@@ -939,13 +930,13 @@ if ($cycle == $DATA_ASSIMILATION_CYCLES) then
       ${MOVE}  *$rm_log[$rm_slot]*  $hidedir
    endif
 
-   # Restore E3SM's timing logic for the first cycle of the next job.
+   # Restore E3SM-FV's timing logic for the first cycle of the next job.
    cd ${CASEROOT}
    ./xmlchange CHECK_TIMING=${CHECK_TIMING}
    cd ${RUNDIR}
 
    # Create a netCDF file which contains the names of DART inflation restart files.
-   # This is needed in order to use the E3SM st_archive mechanisms for keeping, 
+   # This is needed in order to use the E3SM-FV st_archive mechanisms for keeping, 
    # in $RUNDIR, history files which are needed for restarts.
    # These special files must be labeled with '.rh.'.
    # St_archive looks in a .r. restart file for the names of these 'restart history' files.
